@extends('layouts.app')
@section('title', 'Carento - Premium Car Dealership')
@section('headerStyle', '1')
@section('content')
@include('sections.hero')
@include('sections.search')
@include('sections.brand')
@include('sections.cars-featured')
@include('sections.cta')
@include('sections.categories')
@include('sections.why-us')
@include('sections.cars-latest')
@include('sections.services')
@include('sections.testimonials')
@include('sections.blog')
@endsection
