@extends('layouts.app')
@section('title', 'Carento - Homepage')
@section('headerStyle', '1')
@section('content')
@include('sections.hero-1')
@include('sections.search-1')
@include('sections.brand')
@include('sections.cars-listing-1')
@include('sections.cta-1')
@include('sections.categories')
@include('sections.why-us')
@include('sections.cta-2')
@include('sections.cars-listing-2')
@include('sections.cta-3')
@include('sections.services')
@include('sections.banners')
@include('sections.testimonials')
@include('sections.car-review')
@include('sections.blog')
@include('sections.app')
@endsection
