<?php

return [
    [
        "id" => 1,
        "name" => 'GMC Sierra 2500HD Denali',
        "image" => 'car-1.png',
        "price" => 100,
        "duration" => '7',
        "carType" => 'Sedans',
        "amenities" => 'Leather upholstery',
        "rating" => 4.5,
        "fuelType" => 'Plug-in Hybrid (PHEV)',
        "location" => 'Machu Picchu',
    ],
    [
        "id" => 2,
        "name" => 'Ford Mustang GT Premium',
        "image" => 'car-2.png',
        "price" => 200,
        "duration" => '5',
        "carType" => 'Hatchbacks',
        "amenities" => 'Heated seats',
        "rating" => 4.7,
        "fuelType" => 'Hybrid (HEV)',
        "location" => 'Great Wall',
    ],
    [
        "id" => 3,
        "name" => 'Mazda MX-5 Miata Club',
        "image" => 'car-3.png',
        "price" => 300,
        "duration" => '10',
        "carType" => 'Convertibles',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.9,
        "fuelType" => 'Electric Vehicle (EV)',
        "location" => 'Eiffel Tower',
    ],
    [
        "id" => 4,
        "name" => 'Subaru Impreza WRX STI',
        "image" => 'car-4.png',
        "price" => 400,
        "duration" => '7',
        "carType" => 'Sedans',
        "amenities" => 'Leather upholstery',
        "rating" => 4.6,
        "fuelType" => 'Diesel',
        "location" => 'Statue of Liberty',
    ],
    [
        "id" => 5,
        "name" => 'Porsche 911 Carrera S',
        "image" => 'car-5.png',
        "price" => 500,
        "duration" => '5',
        "carType" => 'Sedans',
        "amenities" => 'Heads-up display',
        "rating" => 4.8,
        "fuelType" => 'Gasoline/Petrol',
        "location" => 'Taj Mahal',
    ],
    [
        "id" => 6,
        "name" => 'Toyota Camry LE Hybrid',
        "image" => 'car-6.png',
        "price" => 100,
        "duration" => '4',
        "carType" => 'SUVs',
        "amenities" => 'Leather upholstery',
        "rating" => 4.4,
        "fuelType" => 'Hydrogen',
        "location" => 'Great Wall',
    ],
    [
        "id" => 7,
        "name" => 'Hyundai Sonata SEL Plus',
        "image" => 'car-7.png',
        "price" => 200,
        "duration" => '7',
        "carType" => 'SUVs',
        "amenities" => 'Adaptive cruise control',
        "rating" => 4.7,
        "fuelType" => 'Plug-in Hybrid (PHEV)',
        "location" => 'Eiffel Tower',
    ],
    [
        "id" => 8,
        "name" => 'Buick Enclave Avenir',
        "image" => 'car-8.png',
        "price" => 300,
        "duration" => '7',
        "carType" => 'SUVs',
        "amenities" => 'Heated seats',
        "rating" => 4.6,
        "fuelType" => 'Hybrid (HEV)',
        "location" => 'Statue of Liberty',
    ],
    [
        "id" => 9,
        "name" => 'Chevrolet Silverado',
        "image" => 'car-9.png',
        "price" => 400,
        "duration" => '5',
        "carType" => 'Coupes',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.5,
        "fuelType" => 'Electric Vehicle (EV)',
        "location" => 'Machu Picchu',
    ],
    [
        "id" => 10,
        "name" => 'Subaru Outback Limited XT',
        "image" => 'car-10.png',
        "price" => 500,
        "duration" => '7',
        "carType" => 'Coupes',
        "amenities" => 'Heated seats',
        "rating" => 4.5,
        "fuelType" => 'Diesel',
        "location" => 'Taj Mahal',
    ],
    [
        "id" => 11,
        "name" => 'Jeep Wrangler Rubicon Unlimited',
        "image" => 'car-11.png',
        "price" => 450,
        "duration" => '5',
        "carType" => 'Compacts',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.8,
        "fuelType" => 'Electric Vehicle (EV)',
        "location" => 'Colosseum',
    ],
    [
        "id" => 12,
        "name" => 'Kia Telluride SX',
        "image" => 'car-12.png',
        "price" => 370,
        "duration" => '7',
        "carType" => 'SUVs',
        "amenities" => 'Heated seats',
        "rating" => 4.7,
        "fuelType" => 'Plug-in Hybrid (PHEV)',
        "location" => 'Pyramids of Giza',
    ],
    [
        "id" => 13,
        "name" => 'Mini Cooper S Hardtop 2 Door',
        "image" => 'car-13.png',
        "price" => 420,
        "duration" => '6',
        "carType" => 'Coupes',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.6,
        "fuelType" => 'Hybrid (HEV)',
        "location" => 'Pompeii',
    ],
    [
        "id" => 14,
        "name" => 'Subaru Impreza WRX STI',
        "image" => 'car-14.png',
        "price" => 330,
        "duration" => '7',
        "carType" => 'Compacts',
        "amenities" => 'Heated seats',
        "rating" => 4.5,
        "fuelType" => 'Diesel',
        "location" => 'Buckingham Palace',
    ],
    [
        "id" => 15,
        "name" => 'Audi Q5 2.0T Premium Plus',
        "image" => 'car-15.png',
        "price" => 410,
        "duration" => '5',
        "carType" => 'SUVs',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.5,
        "fuelType" => 'Plug-in Hybrid (PHEV)',
        "location" => 'Eiffel Tower',
    ],
    [
        "id" => 16,
        "name" => 'Cadillac XT6 Premium Luxury',
        "image" => 'car-16.png',
        "price" => 340,
        "duration" => '6',
        "carType" => 'Coupes',
        "amenities" => 'Heated seats',
        "rating" => 4.4,
        "fuelType" => 'Hybrid (HEV)',
        "location" => 'Statue of Liberty',
    ],
    [
        "id" => 17,
        "name" => 'Chevrolet Bolt EV Premier',
        "image" => 'car-17.png',
        "price" => 470,
        "duration" => '7',
        "carType" => 'Compacts',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.3,
        "fuelType" => 'Electric Vehicle (EV)',
        "location" => 'Machu Picchu',
    ],
    [
        "id" => 18,
        "name" => 'Ford Explorer Limited',
        "image" => 'car-18.png',
        "price" => 530,
        "duration" => '5',
        "carType" => 'SUVs',
        "amenities" => 'Heated seats',
        "rating" => 4.2,
        "fuelType" => 'Diesel',
        "location" => 'Taj Mahal',
    ],
    [
        "id" => 19,
        "name" => 'Lexus RC 300 F Sport',
        "image" => 'car-19.png',
        "price" => 490,
        "duration" => '7',
        "carType" => 'Coupes',
        "amenities" => 'Sunroof/Moonroof',
        "rating" => 4.1,
        "fuelType" => 'Plug-in Hybrid (PHEV)',
        "location" => 'Colosseum',
    ],
    [
        "id" => 20,
        "name" => 'Nissan Rogue SV AWD',
        "image" => 'car-20.png',
        "price" => 380,
        "duration" => '5',
        "carType" => 'Compacts',
        "amenities" => 'Heated seats',
        "rating" => 4.0,
        "fuelType" => 'Hybrid (HEV)',
        "location" => 'Pyramids of Giza',
    ],
];
